### ISSUE TITLE
STS->MN: STS bibliographic entries should be faithfully converted

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#13] opened 2021-06-23 04:21 UTC
Conversion of "ISO Guide" documents are wrong. Should be "ISO Guide 2:2004" instead of "ISO 2:2004"

The other patterns are "ISO/{TS,TR}", "IWA" and "ISO/{stage} {TS,TR}".

e.g.

```xml
            <ref content-type="standard" id="ref_20">
                <label>[20]</label>
                <std std-id="iso:std:iso-iec:guide:2:ed-8:en" type="dated">
                    <std-ref>ISO/IEC Guide 2:2004</std-ref>
                    ,
                    <title>Standardization and related activities — General vocabulary</title>
                </std>
            </ref>
            <ref content-type="standard" id="ref_21">
                <label>[21]</label>
                <std std-id="iso:std:iso-iec:guide:71:ed-2:en" type="dated">
                    <std-ref>ISO/IEC Guide 71:2014</std-ref>
                    ,
                    <title>Guide for addressing accessibility in standards</title>
                </std>
            </ref>
...
```

```
* [[[ISO-IEC_2-2004,ISO/IEC 2:2004]]] ISO/IEC Guide 2:2004, Standardization and related activities -- General vocabulary

* [[[ISO-IEC_71-2014,ISO/IEC 71:2014]]] ISO/IEC Guide 71:2014, Guide for addressing accessibility in standards

* [[[ISO_73-2009,ISO 73:2009]]] ISO Guide 73:2009, Risk management -- Vocabulary

* [[[ISO_82-2014,ISO 82:2014]]] ISO Guide 82:2014, Guidelines for addressing sustainability in standards
```

**Comment by Intelligent2013** [comment] 2021-11-06 11:57
The issue isn't repeated. Closing.

1. ISO/IEC Guide 2:2004
source STS xml:
```xml
<ref content-type="standard" id="ref_20">
	<label>[20]</label>
	<std std-id="iso:std:iso-iec:guide:2:ed-8:en" type="dated">
		<std-ref>ISO/IEC Guide 2:2004</std-ref>, <title>Standardization and related activities — General vocabulary</title>
	</std>
</ref>
```

adoc (mnconvert):
```adoc
* [[[ref_20,(20)ISO/IEC Guide 2:2004]]], _Standardization and related activities — General vocabulary_
```

metanorma xml:
```xml
<bibitem id="ref_20" type="standard">
	<fetched>2021-11-05</fetched>
	<title type="title-intro" format="text/plain" language="en" script="Latn">Standardization and related activities</title>
	<title type="title-main" format="text/plain" language="en" script="Latn">General vocabulary</title>
	<title type="main" format="text/plain" language="en" script="Latn">Standardization and related activities&#8201;&#8212;&#8201;General vocabulary</title>
	<uri type="src">https://www.iso.org/standard/39976.html</uri>
	<uri type="obp">https://www.iso.org/obp/ui/#!iso:std:39976:en</uri>
	<uri type="rss">https://www.iso.org/contents/data/standard/03/99/39976.detail.rss</uri>
	<uri type="pub">https://isotc.iso.org/livelink/livelink/Open/8389141</uri>
	<docidentifier type="ISO">ISO/IEC Guide 2:2004</docidentifier>
	<docidentifier type="metanorma">[5]</docidentifier>
	<docidentifier type="URN">URN urn:iso:std:iso-iec:2:stage-90.60:ed-8:en</docidentifier>
	...
```


2. ISO/TS 9002:2016
source STS xml:
```xml
<ref content-type="standard" id="ref_4">
	<label>[3]</label>
	<std std-id="iso:std:iso:ts:9002:ed-1:en" type="dated">
		<std-ref>ISO/TS 9002:2016<?doi https://doi.org/10.3403/30330644?>
		</std-ref>, <title>Quality management systems — Guidelines for the application of ISO 9001:2015</title>
	</std>
</ref>

adoc (mnconvert):
```adoc
* [[[ref_4,(3)ISO/TS 9002:2016]]], _Quality management systems — Guidelines for the application of ISO 9001:2015_
```

metanorma xml:
```xml
<bibitem id="ref_4" type="standard">
  <title format="text/plain">Quality management systems &#8212; Guidelines for the application of ISO 9001:2015</title>
  <docidentifier type="metanorma">[1]</docidentifier>
  <docidentifier type="ISO">ISO/TS 9002:2016</docidentifier>
  <docnumber>9002</docnumber>
	...
```

**Closed by Intelligent2013** 2021-11-06 11:57 UTC
