### ISSUE TITLE
STS -> MN: Correct markup of sources in Terms and Definitions section

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#61] opened 2021-08-13 03:43 UTC
*In relation https://github.com/metanorma/metanorma-bsi/issues/30*

When source reference is tagged as *modified*, is enough with putting a comma (`,`) at the end of the markup source.
See [Terms and Definitions](https://www.metanorma.org/author/topics/document-format/section-terms/#defining-terms-the-terms-and-definitions-section).

For example, from *bs-8887-2009*, instead of:
````
[.source]
<<ISO_9000_2005,ISO 9000:2005,3.4.1,modified>>
````

it should be:
````
[.source]
<<ISO_9000_2005,ISO 9000:2005,3.4.1>>,
````

and renders:
![issue8-0](https://user-images.githubusercontent.com/33627611/129301935-36682618-a5a6-49b1-9db8-63cd314eb564.PNG)

(The m-dash must be removed.)

In addition, in *bs-8887-2009*, there are several sources are in blank.

Markup:
````
=== disposal

any operation which is not recovery even where the operation has as a
secondary consequence the reclamation of substances or energy

[.source]
<<Waste Framework Directive 1>>
````

Output:
![issue8-1](https://user-images.githubusercontent.com/33627611/129301640-1bef37a2-dfcd-4373-8b33-eb0925ecf8bd.PNG)

Markup:
````
=== geometrical product specification
alt:[GPS]

system for defining the shape (geometry), dimensions and surface characteristics of a workpiece

[.source]
<<BS 8888:2008>>
````

Output:
![issue8-2](https://user-images.githubusercontent.com/33627611/129301642-a6acec73-ffc8-454c-b99c-b0fa998e1617.PNG)

Markup:
````
=== technical product document
alt:[TPD]

means of conveying all or part of a design definition or specification of a
product for manufacturing and verification purposes

[.source]
<<BS 8888:2008>>
````
Output:
![issue8-3](https://user-images.githubusercontent.com/33627611/129301646-794a6c70-18e1-415b-847d-7e103179abd0.PNG)

**Comment by Intelligent2013** [comment] 2021-08-17 15:07
This issue also relates to https://github.com/metanorma/mnconvert/issues/7

**Comment by Intelligent2013** [comment] 2021-08-17 21:14
Done:
![image](https://user-images.githubusercontent.com/5559926/129798374-6b717220-9489-4135-9478-689cc211f600.png)
![image](https://user-images.githubusercontent.com/5559926/129798420-f5aceaac-63d5-4ba0-a4af-5cc02862d55d.png)
![image](https://user-images.githubusercontent.com/5559926/129798456-3e93649b-dde0-4a0b-90a3-1f359cdd0cee.png)
![image](https://user-images.githubusercontent.com/5559926/129798498-a69dc268-1b6e-424c-ab01-6b7a93fbdf05.png)

**Comment by manuel489** [comment] 2021-08-19 16:49
@Intelligent2013 there a couple of "little issues" in *bs-8887-2009* that come directly from XML source.

1. There is an outcast closing bracket in one of the source references:
````
=== recovery

process in which waste material is either treated to release materials in a form where they can be used again, or used as fuel in energy recovery

[.source]
<<prIEC_6254,prIEC 6254, 3.2.20].>>
````

renders:
![issue1-generated](https://user-images.githubusercontent.com/33627611/130108307-e280f66f-8c2c-400e-8895-03711d9e5b8c.PNG)

original:
![issue1-original](https://user-images.githubusercontent.com/33627611/130108381-04c0bebb-4acf-476e-a364-5914c0441d1e.PNG)


XML source:
```xml
<tbx:definition>process in which waste material is either treated to release materials in a form where they can be used again, or used as fuel in energy recovery</tbx:definition>
<tbx:source>prIEC 6254, <bold>3.2.20</bold>].</tbx:source>
```

2. There is an NOTE block that should be encoded with `====` delimiting characters.

I mean, this:
````
NOTE: There is an effect of re-use on whole-life cost C~wl~. That is: 


stem:[<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1"><mrow><msub><mtext>c</mtext><mrow><mtext>wl</mtext></mrow></msub><mtext>=</mtext><mfrac><mrow><msub><mtext>c</mtext><mrow><mtext>oem</mtext></mrow></msub><msub><mrow><mtext>+nc</mtext></mrow><mrow><mtext>rmf</mtext></mrow></msub><msub><mrow><mtext>+c</mtext></mrow><mrow><mtext>eol</mtext></mrow></msub></mrow><mrow><mtext>1+n</mtext></mrow></mfrac></mrow></math>]

_where_

__C__~oe~~m~__is the cost of original manufacture;__

__C__~rm~~f~__is the cost of re-manufacturing;__

__C__~eo~~l~__is the {{end-of-life}} cost;__

__n is the number of times the product is re-manufactured.__
````

should be this instead:

````
[NOTE]
====
There is an effect of re-use on whole-life cost C~wl~. That is: 

stem:[<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1"><mrow><msub><mtext>c</mtext><mrow><mtext>wl</mtext></mrow></msub><mtext>=</mtext><mfrac><mrow><msub><mtext>c</mtext><mrow><mtext>oem</mtext></mrow></msub><msub><mrow><mtext>+nc</mtext></mrow><mrow><mtext>rmf</mtext></mrow></msub><msub><mrow><mtext>+c</mtext></mrow><mrow><mtext>eol</mtext></mrow></msub></mrow><mrow><mtext>1+n</mtext></mrow></mfrac></mrow></math>]

_where_

__C__~oe~~m~__ is the cost of original manufacture;__

__C__~rm~~f~__ is the cost of re-manufacturing;__

__C__~eo~~l~__ is the {{end-of-life}} cost;__

__n is the number of times the product is re-manufactured.__
====
````

(Also, there should be a white space between the inline equations and their respective descriptions.)

But again, this error comes from XML source:
```xml
<tbx:note>There is an effect of re-use on whole-life cost C<sub>wl</sub>. That is:
</tbx:note>
<tbx:definition>
<disp-formula><mml:math id="mml_m1"><mml:mrow><mml:msub><mml:mtext>c</mml:mtext><mml:mrow><mml:mtext>wl</mml:mtext></mml:mrow></mml:msub><mml:mtext>=</mml:mtext><mml:mfrac><mml:mrow><mml:msub><mml:mtext>c</mml:mtext><mml:mrow><mml:mtext>oem</mml:mtext></mml:mrow></mml:msub><mml:msub><mml:mrow><mml:mtext>+nc</mml:mtext></mml:mrow><mml:mrow><mml:mtext>rmf</mml:mtext></mml:mrow></mml:msub><mml:msub><mml:mrow><mml:mtext>+c</mml:mtext></mml:mrow><mml:mrow><mml:mtext>eol</mml:mtext></mml:mrow></mml:msub></mml:mrow><mml:mrow><mml:mtext>1+n</mml:mtext></mml:mrow></mml:mfrac></mml:mrow></mml:math></disp-formula>
</tbx:definition>
<tbx:tig>
<tbx:term>whole-life costs</tbx:term>
<tbx:partOfSpeech value="noun"/>
</tbx:tig>
</tbx:langSet>
</tbx:termEntry>
<p><italic>where</italic></p>
<p><italic>C</italic><sub>oe</sub><sub>m</sub><italic>is the cost of original manufacture;</italic></p>
<p><italic>C</italic><sub>rm</sub><sub>f</sub><italic>is the cost of re-manufacturing;</italic></p>
<p><italic>C</italic><sub>eo</sub><sub>l</sub><italic>is the <named-content content-type="term" xlink:href="#term_3.13">end-of-life</named-content> cost;</italic></p>
<p><italic>n is the number of times the product is re-manufactured.</italic></p>
```

So, I'm not sure if we should fix them or leave them as they are.
@ronaldtse, what do you think?

**Comment by ronaldtse** [comment] 2021-08-20 01:18
@manuel489 in this case the issue is not ours to fix. Can you file this issue at mn-samples-bsi and we report back to BSI to fix it at source?

**Comment by ronaldtse** [comment] 2021-08-20 03:40
Closing this since the relevant issues have been filed in mn-samples-bsi. Thanks @manuel489 !

**Closed by ronaldtse** 2021-08-20 03:40 UTC
Labels: bug
